'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication1.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _001_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("001_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _001_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("001_02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _001_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("001_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _001_05() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("001_05", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _001_06() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("001_06", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _001_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("001_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _001_37() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("001_37", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _001_58() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("001_58", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _37708_O1AVP3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("37708-O1AVP3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _52() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("52", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _99() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("99", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _991() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("991", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property actualiser() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("actualiser", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Amalgama() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Amalgama", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property apicetomia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("apicetomia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ausencia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ausencia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property base_de_cementacion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("base_de_cementacion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bin_Full() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bin-Full", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blanco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blanco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blanqueamiento() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blanqueamiento", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bracket() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bracket", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property button_cancel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_cancel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property button_cancel1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_cancel1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property button_cancel2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_cancel2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property button_ok() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_ok", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property button_ok1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_ok1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Calendar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Calendar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Calendar68() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Calendar68", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cancelar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancelar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property carillas_de_porcelana() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("carillas_de_porcelana", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Ccleaner_3D_v2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Ccleaner 3D v2 ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Chief_of_Staff_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chief of Staff 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Copia__de_plan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Copia  de plan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property corona() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("corona", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property corona_metalica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("corona metalica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property corona_metalicaodontopediatria() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("corona metalicaodontopediatria", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property corona_venneracrilico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("corona venneracrilico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property corona_vennerembiolo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("corona vennerembiolo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CRISTAL_KEY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CRISTAL KEY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CRISTAL_TRASH_FULL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CRISTAL TRASH FULL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CRISTAL_TRASH_FULL1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CRISTAL TRASH FULL1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Critical() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Critical", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property curetaje() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("curetaje", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property demo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("demo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dentist_Add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dentist Add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dentist_Add1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dentist Add1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dentist_Delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dentist Delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dentist_Edit_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dentist Edit 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dentist_Search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dentist Search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dentistas_en_cumbres_icono() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dentistas-en-cumbres-icono", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dentistry() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dentistry", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property desgastes_proximales() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("desgastes_proximales", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property diente() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("diente", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property diente2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("diente2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property doctor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("doctor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Doctor_1_Add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Doctor 1 Add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Doctor_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Doctor-icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DOLLAR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DOLLAR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DOLLAR_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DOLLAR 24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property edit_add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edit_add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property editar1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("editar1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property endodoncia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("endodoncia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property extraccion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("extraccion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ferulizacion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ferulizacion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property guardar1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("guardar1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_account_circle_black_24dp_1x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_account_circle_black_24dp_1x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_account_circle_white_48dp_2x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_account_circle_white_48dp_2x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_add_a_photo_black_24dp_1x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_add_a_photo_black_24dp_1x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_add_a_photo_black_48dp_2x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_add_a_photo_black_48dp_2x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_add_a_photo_white_48dp_2x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_add_a_photo_white_48dp_2x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_add_black_48dp_1x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_add_black_48dp_1x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_adjust_black_24dp_1x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_adjust_black_24dp_1x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_attach_money_white_48dp_2x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_attach_money_white_48dp_2x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_block_black_24dp_1x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_block_black_24dp_1x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_block_black_24dp_2x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_block_black_24dp_2x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_build_white_48dp_2x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_build_white_48dp_2x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_cached_black_24dp_1x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_cached_black_24dp_1x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_close_black_24dp_1x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_close_black_24dp_1x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_close_black_24dp_1x1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_close_black_24dp_1x1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_content_paste_white_48dp_2x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_content_paste_white_48dp_2x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_create_new_folder_black_24dp_1x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_create_new_folder_black_24dp_1x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_date_range_black_24dp_1x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_date_range_black_24dp_1x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_description_white_48dp_2x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_description_white_48dp_2x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_doctor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_doctor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_doctor_female() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_doctor_female", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_done_black_24dp_1x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_done_black_24dp_1x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_error_white_48dp_2x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_error_white_48dp_2x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_event_note_white_24dp_2x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_event_note_white_24dp_2x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_event_note_white_48dp_2x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_event_note_white_48dp_2x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_find_in_page_black_24dp_1x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_find_in_page_black_24dp_1x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_find_in_page_black_24dp_2x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_find_in_page_black_24dp_2x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_help_outline_black_24dp_1x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_help_outline_black_24dp_1x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_help_outline_black_24dp_2x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_help_outline_black_24dp_2x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_help_outline_black_48dp_2x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_help_outline_black_48dp_2x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_help_outline_white_48dp_2x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_help_outline_white_48dp_2x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_insert_chart_white_48dp_2x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_insert_chart_white_48dp_2x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_lock_black_24dp_1x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_lock_black_24dp_1x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_loop_black_24dp_1x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_loop_black_24dp_1x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_mode_edit_black_24dp_1x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_mode_edit_black_24dp_1x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_monetization_on_black_24dp_2x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_monetization_on_black_24dp_2x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_perm_identity_white_48dp_1x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_perm_identity_white_48dp_1x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_perm_identity_white_48dp_2x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_perm_identity_white_48dp_2x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_person_black_48dp_1x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_person_black_48dp_1x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_person_black_48dp_2x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_person_black_48dp_2x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_power_settings_new_black_24dp_1x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_power_settings_new_black_24dp_1x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_print_black_24dp_2x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_print_black_24dp_2x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_refresh_black_48dp_1x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_refresh_black_48dp_1x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_remove_black_24dp_1x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_remove_black_24dp_1x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_replay_black_48dp_1x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_replay_black_48dp_1x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_restore_black_24dp_1x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_restore_black_24dp_1x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_save_black_48dp_1x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_save_black_48dp_1x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_save_white_48dp_1x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_save_white_48dp_1x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_view_comfy_white_48dp_1x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_view_comfy_white_48dp_1x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ic_vpn_key_black_48dp_1x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ic_vpn_key_black_48dp_1x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_doc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon-doc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Icon_history() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Icon-history", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property incrustaciones() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("incrustaciones", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property inf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property informe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("informe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ODONTECH_FONDO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ODONTECH FONDO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ODONTOTECH() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ODONTOTECH", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property patient() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("patient", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Patient_Boy_1_Add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Patient Boy 1 Add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Patient_Girl_1_Green_Add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Patient Girl 1 Green Add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Patient_Girl_2_Add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Patient Girl 2 Add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Patient_Man_1_Blue_Edit_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Patient Man 1 Blue Edit 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Patient_Man_1_Search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Patient Man 1 Search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Patient_Man_2_Add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Patient Man 2 Add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Patient_Man_2_Add1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Patient Man 2 Add1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Patient_Man_2_Delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Patient Man 2 Delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Patient_Man_2_Edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Patient Man 2 Edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Patient_Man_2_Green_Add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Patient Man 2 Green Add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Patient_Woman_1_Check() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Patient Woman 1 Check", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Patient_Woman_2_Add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Patient Woman 2 Add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property printmgr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printmgr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property puente_acrilico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("puente acrilico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property puente_ausente() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("puente ausente", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property puente_ausente1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("puente ausente1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property puente_combinado() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("puente combinado", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property puente_embiolo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("puente embiolo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property puente_porcelana() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("puente porcelana", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pulpotomia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pulpotomia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property radiografia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("radiografia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property radiology() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("radiology", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property recubrimiento_pulpar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("recubrimiento pulpar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scanner1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scanner1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Search1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Search1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shutterstock_194951279() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shutterstock_194951279", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shutterstock_1949512792() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shutterstock_1949512792", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shutterstock_19495127921() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shutterstock_19495127921", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shutterstock_1949512793() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shutterstock_1949512793", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shutterstock_1949512794() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shutterstock_1949512794", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Teeth_and_Gums() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Teeth and Gums", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Teeth_and_Gums1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Teeth and Gums1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Teeth_and_Gums2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Teeth and Gums2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Teeth_and_Gums21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Teeth and Gums21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Teeth_and_Gums22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Teeth and Gums22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tooth_2_Add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tooth 2 Add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tooth_2_Clean() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tooth 2 Clean", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tooth_2_Delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tooth 2 Delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Tooth_2_View() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Tooth 2 View", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tratamiento_emergencia() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tratamiento emergencia", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property User() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Users() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Users", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property yaquet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("yaquet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property yaquet_biolo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("yaquet biolo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
